### ISSUE TITLE
Raw TCP sockets don't work on replit

### ISSUE THREAD

**Issue by programmeruser2** [leon332157/replish#4]
For this server to actually run on repl.it, you would have to use a TCP tunnel to make it work.

**Comment by leon332157** [comment]
The implementation idea is to use websocket, which I have tested to work with a repl.

**Comment by zplusfour** [comment]
i honestly got bored of this

**Comment by leon332157** [comment]
Can you add a dialog in gerPortAuto so people can choose which port to use when there are multiple open local ports?

**Comment by zplusfour** [comment]
filename, line number please?

**Comment by leon332157** [comment]
Already finished that feature. If you want to help me build up the ssh server while I finalize the http server, feel free to do so. For example, you can build a working server and add in direct-tcp-ip (ssh port forward) so I can connect the websocket with the ssh server.

**Comment by RayhanADev** [comment]
Should this issue be closed?

**Comment by programmeruser2** [comment]
> Should this issue be closed?
Probably.
